version: "3"

services:
  
  # PostgreSQL
  postgres:
    image: postgres
    container_name: container-postgresql
    restart: "no"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"