name: Build feature

on:
  push:
    branches:
      - "feature-**"

jobs:
  unit_test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout
        uses: actions/checkout@v2

      - name: 2. Creating PHP 7.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.3"
          extensions: xdebug

      - name: 3. Validate composer.json
        run: composer validate

      - name: 4. Install dependencies
        run: composer install --no-interaction --no-suggest --prefer-dist

      - name: 5. Run tests
        run: composer test:details

      - name: 6. Run coverage
        run: composer test:coverage

  integration_test:
    name: Integration tests
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout
        uses: actions/checkout@v2

      - name: 2. Creating PHP 7.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.3"
          extensions: xdebug

      - name: 3. Validate composer.json
        run: composer validate

      - name: 4. Install dependencies
        run: composer install --no-interaction --no-suggest --prefer-dist

      - name: 5. Copy .env.example
        run: php -r "if (file_exists('.env') === false) { copy('.env.example', '.env'); }"

      - name: 6. Run tests
        run: composer test_integration:details

      - name: 7. Run coverage
        run: composer test_integration:coverage
        
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        
        ports:
          - 5432:5432

        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5